# Generated by Django 5.1.2 on 2024-10-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participations', through='poker_data.EventParticipation', to='poker_data.player'),
        ),
    ]
