# Generated by Django 5.1.2 on 2024-12-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_data', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='chips_bought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='poker_data.EventParticipation', to='poker_data.player'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='poker_data.player'),
        ),
    ]
