# Generated by Django 5.1.2 on 2024-12-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_data', '0003_eventparticipation_chips_bought_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='chips_bought',
        ),
    ]
