# Generated by Django 5.1.2 on 2024-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_data', '0004_remove_eventparticipation_chips_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='buy_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
