# Generated by Django 5.1.2 on 2025-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_data', '0005_eventparticipation_buy_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remaining_chips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
